-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 12:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smilesys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smilesys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smilesys` DEFAULT CHARACTER SET utf8 ;
USE `smilesys` ;

-- -----------------------------------------------------
-- Table `smilesys`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`Pacientes` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `folio` INT NOT NULL,
  `fecIngreso` DATE NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `apePat` VARCHAR(45) NOT NULL,
  `apeMat` VARCHAR(45) NULL DEFAULT NULL,
  `calle` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `codPos` VARCHAR(10) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telCasa` VARCHAR(10) NOT NULL,
  `telCel` VARCHAR(10) NULL DEFAULT NULL,
  `fecNacimiento` DATE NOT NULL,
  `lugNacimiento` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `ocupacion` VARCHAR(45) NOT NULL,
  `estCivil` VARCHAR(45) NOT NULL,
  `perResp` VARCHAR(45) NULL DEFAULT NULL,
  `motConsulta` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`atm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`atm` (
  `idAtm` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NULL DEFAULT NULL,
  `linMedia` TINYINT(11) NULL DEFAULT NULL,
  `habitos` TINYINT(11) NULL DEFAULT NULL,
  `bruxismo` TINYINT(11) NULL DEFAULT NULL,
  `chasquidos` TINYINT(11) NULL DEFAULT NULL,
  `infChasquido` VARCHAR(45) NULL DEFAULT NULL,
  `crepitacion` TINYINT(11) NULL DEFAULT NULL,
  `dolor` TINYINT(11) NULL DEFAULT NULL,
  `infDolor` VARCHAR(45) NULL DEFAULT NULL,
  `maxAbertura` TINYINT(11) NULL DEFAULT NULL,
  `izquierdo` TINYINT(11) NULL DEFAULT NULL,
  `derecho` TINYINT(11) NULL DEFAULT NULL,
  `potrusion` TINYINT(11) NULL DEFAULT NULL,
  `regresion` TINYINT(11) NULL DEFAULT NULL,
  `peso` TINYINT(11) NULL DEFAULT NULL,
  `talla` TINYINT(11) NULL DEFAULT NULL,
  `temp` TINYINT(11) NULL DEFAULT NULL,
  `pa` TINYINT(11) NULL DEFAULT NULL,
  `pulso` TINYINT(11) NULL DEFAULT NULL,
  `fr` TINYINT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idAtm`),
  INDEX `fk_pac_atm` (`idPaciente` ASC),
  CONSTRAINT `fk_atm_pac`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `smilesys`.`Pacientes` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`histClinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`histClinico` (
  `idClinico` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NULL DEFAULT NULL,
  `esmalte` TINYINT(11) NULL DEFAULT NULL,
  `dentina` TINYINT(11) NULL DEFAULT NULL,
  `raiz` TINYINT(11) NULL DEFAULT NULL,
  `huesos` TINYINT(11) NULL DEFAULT NULL,
  `encia` TINYINT(11) NULL DEFAULT NULL,
  `inEpil` TINYINT(11) NULL DEFAULT NULL,
  `lengua` TINYINT(11) NULL DEFAULT NULL,
  `pulpo` TINYINT(11) NULL DEFAULT NULL,
  `velPal` TINYINT(11) NULL DEFAULT NULL,
  `carrillo` TINYINT(11) NULL DEFAULT NULL,
  `soMordidaH` TINYINT(11) NULL DEFAULT NULL,
  `soMordidaV` TINYINT(11) NULL DEFAULT NULL,
  `morAbierta` TINYINT(11) NULL DEFAULT NULL,
  `desBruxismo` TINYINT(11) NULL DEFAULT NULL,
  `anoclusion` TINYINT(11) NULL DEFAULT NULL,
  `simetrica` TINYINT(11) NULL DEFAULT NULL,
  `asimetrica` TINYINT(11) NULL DEFAULT NULL,
  `braquicefalo` TINYINT(11) NULL DEFAULT NULL,
  `mesocefalo` TINYINT(11) NULL DEFAULT NULL,
  `dolicefalo` TINYINT(11) NULL DEFAULT NULL,
  `recto` TINYINT(11) NULL DEFAULT NULL,
  `concavo` TINYINT(11) NULL DEFAULT NULL,
  `convexo` TINYINT(11) NULL DEFAULT NULL,
  `sarampion` TINYINT(11) NULL DEFAULT NULL,
  `viruela` TINYINT(11) NULL DEFAULT NULL,
  `parotidis` TINYINT(11) NULL DEFAULT NULL,
  `diabetes` TINYINT(11) NULL DEFAULT NULL,
  `hipertension` TINYINT(11) NULL DEFAULT NULL,
  `tiroides` TINYINT(11) NULL DEFAULT NULL,
  `hipotiroidismo` TINYINT(11) NULL DEFAULT NULL,
  `proCoagulacion` TINYINT(11) NULL DEFAULT NULL,
  `alergias` TINYINT(11) NULL DEFAULT NULL,
  `descAlergias` VARCHAR(45) NULL DEFAULT NULL,
  `emergencia` TINYINT(11) NULL DEFAULT NULL,
  `revision` TINYINT(11) NULL DEFAULT NULL,
  `canes` TINYINT(11) NULL DEFAULT NULL,
  `puente` TINYINT(11) NULL DEFAULT NULL,
  `extraccion` TINYINT(11) NULL DEFAULT NULL,
  `prostodoncia` TINYINT(11) NULL DEFAULT NULL,
  `buena` TINYINT(11) NULL DEFAULT NULL,
  `mala` TINYINT(11) NULL DEFAULT NULL,
  `tomAlcohol` TINYINT(11) NULL DEFAULT NULL,
  `fuma` TINYINT(11) NULL DEFAULT NULL,
  `apRespiratorio` TINYINT(11) NULL DEFAULT NULL,
  `apCardiovascular` TINYINT(11) NULL DEFAULT NULL,
  `apDigestivo` TINYINT(11) NULL DEFAULT NULL,
  `sisNervioso` TINYINT(11) NULL DEFAULT NULL,
  `apUrinario` TINYINT(11) NULL DEFAULT NULL,
  `cicMestrual` TINYINT(11) NULL DEFAULT NULL,
  `infCicMes` VARCHAR(45) NULL DEFAULT NULL,
  `embarazo` TINYINT(11) NULL DEFAULT NULL,
  `meses` TINYINT(11) NULL DEFAULT NULL,
  `prg1` TINYINT(11) NULL DEFAULT NULL,
  `prg2` VARCHAR(45) NULL DEFAULT NULL,
  `prg3` TINYINT(11) NULL DEFAULT NULL,
  `infPrg3` VARCHAR(45) NULL DEFAULT NULL,
  `prg4` TINYINT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idClinico`),
  INDEX `fk_pac_histcli` (`idPaciente` ASC),
  CONSTRAINT `fk_hist_clin_pac`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `smilesys`.`Pacientes` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`odontograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`odontograma` (
  `idOdontograma` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NULL DEFAULT NULL,
  `d18` TINYINT(11) NULL DEFAULT NULL,
  `infD18` VARCHAR(60) NULL DEFAULT NULL,
  `d17` TINYINT(11) NULL DEFAULT NULL,
  `infD17` VARCHAR(60) NULL DEFAULT NULL,
  `d16` TINYINT(11) NULL DEFAULT NULL,
  `infD16` VARCHAR(60) NULL DEFAULT NULL,
  `d15` TINYINT(11) NULL DEFAULT NULL,
  `infD15` VARCHAR(60) NULL DEFAULT NULL,
  `d14` TINYINT(11) NULL DEFAULT NULL,
  `infD14` VARCHAR(60) NULL DEFAULT NULL,
  `d13` TINYINT(11) NULL DEFAULT NULL,
  `infD13` VARCHAR(60) NULL DEFAULT NULL,
  `d12` TINYINT(11) NULL DEFAULT NULL,
  `infD12` VARCHAR(60) NULL DEFAULT NULL,
  `d11` TINYINT(11) NULL DEFAULT NULL,
  `infD11` VARCHAR(60) NULL DEFAULT NULL,
  `d21` TINYINT(11) NULL DEFAULT NULL,
  `infD21` VARCHAR(45) NULL DEFAULT NULL,
  `d22` TINYINT(11) NULL DEFAULT NULL,
  `infD22` VARCHAR(45) NULL DEFAULT NULL,
  `d23` TINYINT(11) NULL DEFAULT NULL,
  `infD23` VARCHAR(45) NULL DEFAULT NULL,
  `d24` TINYINT(11) NULL DEFAULT NULL,
  `infD24` VARCHAR(45) NULL DEFAULT NULL,
  `d25` TINYINT(11) NULL DEFAULT NULL,
  `infD25` VARCHAR(45) NULL DEFAULT NULL,
  `d26` TINYINT(11) NULL DEFAULT NULL,
  `infD26` VARCHAR(45) NULL DEFAULT NULL,
  `d27` TINYINT(11) NULL DEFAULT NULL,
  `infD27` VARCHAR(45) NULL DEFAULT NULL,
  `d28` TINYINT(11) NULL DEFAULT NULL,
  `infD28` VARCHAR(45) NULL DEFAULT NULL,
  `d48` TINYINT(11) NULL DEFAULT NULL,
  `infD48` VARCHAR(45) NULL DEFAULT NULL,
  `d47` TINYINT(11) NULL DEFAULT NULL,
  `infD47` VARCHAR(45) NULL DEFAULT NULL,
  `d46` TINYINT(11) NULL DEFAULT NULL,
  `infD46` VARCHAR(45) NULL DEFAULT NULL,
  `d45` TINYINT(11) NULL DEFAULT NULL,
  `infD45` VARCHAR(45) NULL DEFAULT NULL,
  `d44` TINYINT(11) NULL DEFAULT NULL,
  `infD44` VARCHAR(45) NULL DEFAULT NULL,
  `d43` TINYINT(11) NULL DEFAULT NULL,
  `infD43` VARCHAR(45) NULL DEFAULT NULL,
  `d42` TINYINT(11) NULL DEFAULT NULL,
  `infD42` VARCHAR(45) NULL DEFAULT NULL,
  `d41` TINYINT(11) NULL DEFAULT NULL,
  `infD41` VARCHAR(45) NULL DEFAULT NULL,
  `d31` TINYINT(11) NULL DEFAULT NULL,
  `infD31` VARCHAR(45) NULL DEFAULT NULL,
  `d32` TINYINT(11) NULL DEFAULT NULL,
  `infD32` VARCHAR(45) NULL DEFAULT NULL,
  `d33` TINYINT(11) NULL DEFAULT NULL,
  `infD33` VARCHAR(45) NULL DEFAULT NULL,
  `d34` TINYINT(11) NULL DEFAULT NULL,
  `infD34` VARCHAR(45) NULL DEFAULT NULL,
  `d35` TINYINT(11) NULL DEFAULT NULL,
  `infD35` VARCHAR(45) NULL DEFAULT NULL,
  `d36` TINYINT(11) NULL DEFAULT NULL,
  `infD36` VARCHAR(45) NULL DEFAULT NULL,
  `d37` TINYINT(11) NULL DEFAULT NULL,
  `infD37` VARCHAR(45) NULL DEFAULT NULL,
  `d38` TINYINT(11) NULL DEFAULT NULL,
  `infD38` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idOdontograma`),
  INDEX `fk_pac_odo` (`idPaciente` ASC),
  CONSTRAINT `fk_odon_pac`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `smilesys`.`Pacientes` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`radiografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`radiografia` (
  `idRadiografia` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NULL DEFAULT NULL,
  `observaciones` VARCHAR(200) NULL DEFAULT NULL,
  `path1` VARCHAR(100) NULL DEFAULT NULL,
  `path2` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idRadiografia`),
  INDEX `fk_pac_radio` (`idPaciente` ASC),
  CONSTRAINT `fk_radio_pac`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `smilesys`.`Pacientes` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`histPagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`histPagos` (
  `idTx` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `costo` TINYINT(11) NULL DEFAULT NULL,
  `cantidad` TINYINT(11) NULL DEFAULT NULL,
  `subtotal` TINYINT(11) NULL DEFAULT NULL,
  `total` TINYINT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idTx`),
  INDEX `fk_pac_histpag` (`idPaciente` ASC),
  CONSTRAINT `fk_hist_pago`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `smilesys`.`Pacientes` (`idPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`pagos` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `idTx` INT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `abono` TINYINT(11) NULL DEFAULT NULL,
  `saldo` TINYINT(11) NULL DEFAULT NULL,
  `total` TINYINT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_histpag_pago` (`idTx` ASC),
  CONSTRAINT `fk_pagos_hispag`
    FOREIGN KEY (`idTx`)
    REFERENCES `smilesys`.`histPagos` (`idTx`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smilesys`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smilesys`.`citas` (
  `idcita` INT NOT NULL AUTO_INCREMENT,
  `idPaciente` INT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `diagnostico` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcita`),
  INDEX `fk_pac_cita` (`idPaciente` ASC),
  CONSTRAINT `fk_cita_pac`
    FOREIGN KEY (`idPaciente`)
    REFERENCES `smilesys`.`Pacientes` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
